// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: camera/camera.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port     string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Ip       string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Filename string `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *Camera) Reset() {
	*x = Camera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{0}
}

func (x *Camera) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Camera) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Camera) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Camera) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Camera) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FindCameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *FindCameraRequest) Reset() {
	*x = FindCameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCameraRequest) ProtoMessage() {}

func (x *FindCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCameraRequest.ProtoReflect.Descriptor instead.
func (*FindCameraRequest) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{1}
}

func (x *FindCameraRequest) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type FindCameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *FindCameraResponse) Reset() {
	*x = FindCameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCameraResponse) ProtoMessage() {}

func (x *FindCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCameraResponse.ProtoReflect.Descriptor instead.
func (*FindCameraResponse) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{2}
}

func (x *FindCameraResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type AddCameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint32  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Camera *Camera `protobuf:"bytes,2,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *AddCameraRequest) Reset() {
	*x = AddCameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCameraRequest) ProtoMessage() {}

func (x *AddCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCameraRequest.ProtoReflect.Descriptor instead.
func (*AddCameraRequest) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{3}
}

func (x *AddCameraRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AddCameraRequest) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type AddCameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Saved bool `protobuf:"varint,2,opt,name=saved,proto3" json:"saved,omitempty"`
}

func (x *AddCameraResponse) Reset() {
	*x = AddCameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCameraResponse) ProtoMessage() {}

func (x *AddCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCameraResponse.ProtoReflect.Descriptor instead.
func (*AddCameraResponse) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{4}
}

func (x *AddCameraResponse) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

type DeleteCameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint32  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Camera *Camera `protobuf:"bytes,2,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *DeleteCameraRequest) Reset() {
	*x = DeleteCameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCameraRequest) ProtoMessage() {}

func (x *DeleteCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCameraRequest.ProtoReflect.Descriptor instead.
func (*DeleteCameraRequest) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCameraRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *DeleteCameraRequest) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type DeleteCameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteCameraResponse) Reset() {
	*x = DeleteCameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCameraResponse) ProtoMessage() {}

func (x *DeleteCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCameraResponse.ProtoReflect.Descriptor instead.
func (*DeleteCameraResponse) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCameraResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetAllCamerasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint32 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *GetAllCamerasRequest) Reset() {
	*x = GetAllCamerasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCamerasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCamerasRequest) ProtoMessage() {}

func (x *GetAllCamerasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCamerasRequest.ProtoReflect.Descriptor instead.
func (*GetAllCamerasRequest) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllCamerasRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetAllCamerasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cameras []*Camera `protobuf:"bytes,1,rep,name=Cameras,proto3" json:"Cameras,omitempty"`
}

func (x *GetAllCamerasResponse) Reset() {
	*x = GetAllCamerasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCamerasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCamerasResponse) ProtoMessage() {}

func (x *GetAllCamerasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCamerasResponse.ProtoReflect.Descriptor instead.
func (*GetAllCamerasResponse) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllCamerasResponse) GetCameras() []*Camera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type GetCameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port string `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetCameraRequest) Reset() {
	*x = GetCameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraRequest) ProtoMessage() {}

func (x *GetCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraRequest.ProtoReflect.Descriptor instead.
func (*GetCameraRequest) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{9}
}

func (x *GetCameraRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *GetCameraRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type GetCameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *GetCameraResponse) Reset() {
	*x = GetCameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_camera_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraResponse) ProtoMessage() {}

func (x *GetCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_camera_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraResponse.ProtoReflect.Descriptor instead.
func (*GetCameraResponse) Descriptor() ([]byte, []int) {
	return file_camera_camera_proto_rawDescGZIP(), []int{10}
}

func (x *GetCameraResponse) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

var File_camera_camera_proto protoreflect.FileDescriptor

var file_camera_camera_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x06, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x34, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x2a, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x22, 0x4b, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1f, 0x0a,
	0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x29,
	0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x73, 0x61, 0x76, 0x65, 0x64, 0x22, 0x4e, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1f, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x07,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22,
	0x34, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x32, 0xbf, 0x02, 0x0a, 0x0c, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x12, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x11, 0x2e, 0x41,
	0x64, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x73, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x42, 0x79, 0x50, 0x6f, 0x72, 0x74, 0x41, 0x6e, 0x64, 0x49, 0x70, 0x12, 0x11,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camera_camera_proto_rawDescOnce sync.Once
	file_camera_camera_proto_rawDescData = file_camera_camera_proto_rawDesc
)

func file_camera_camera_proto_rawDescGZIP() []byte {
	file_camera_camera_proto_rawDescOnce.Do(func() {
		file_camera_camera_proto_rawDescData = protoimpl.X.CompressGZIP(file_camera_camera_proto_rawDescData)
	})
	return file_camera_camera_proto_rawDescData
}

var file_camera_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_camera_camera_proto_goTypes = []interface{}{
	(*Camera)(nil),                // 0: Camera
	(*FindCameraRequest)(nil),     // 1: FindCameraRequest
	(*FindCameraResponse)(nil),    // 2: FindCameraResponse
	(*AddCameraRequest)(nil),      // 3: AddCameraRequest
	(*AddCameraResponse)(nil),     // 4: AddCameraResponse
	(*DeleteCameraRequest)(nil),   // 5: DeleteCameraRequest
	(*DeleteCameraResponse)(nil),  // 6: DeleteCameraResponse
	(*GetAllCamerasRequest)(nil),  // 7: GetAllCamerasRequest
	(*GetAllCamerasResponse)(nil), // 8: GetAllCamerasResponse
	(*GetCameraRequest)(nil),      // 9: GetCameraRequest
	(*GetCameraResponse)(nil),     // 10: GetCameraResponse
}
var file_camera_camera_proto_depIdxs = []int32{
	0,  // 0: FindCameraRequest.camera:type_name -> Camera
	0,  // 1: AddCameraRequest.camera:type_name -> Camera
	0,  // 2: DeleteCameraRequest.camera:type_name -> Camera
	0,  // 3: GetAllCamerasResponse.Cameras:type_name -> Camera
	0,  // 4: GetCameraResponse.camera:type_name -> Camera
	1,  // 5: CameraWorker.FindCamera:input_type -> FindCameraRequest
	3,  // 6: CameraWorker.AddCamera:input_type -> AddCameraRequest
	5,  // 7: CameraWorker.DeleteCamera:input_type -> DeleteCameraRequest
	7,  // 8: CameraWorker.GetAllCameras:input_type -> GetAllCamerasRequest
	9,  // 9: CameraWorker.GetCameraByPortAndIp:input_type -> GetCameraRequest
	2,  // 10: CameraWorker.FindCamera:output_type -> FindCameraResponse
	4,  // 11: CameraWorker.AddCamera:output_type -> AddCameraResponse
	6,  // 12: CameraWorker.DeleteCamera:output_type -> DeleteCameraResponse
	8,  // 13: CameraWorker.GetAllCameras:output_type -> GetAllCamerasResponse
	10, // 14: CameraWorker.GetCameraByPortAndIp:output_type -> GetCameraResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_camera_camera_proto_init() }
func file_camera_camera_proto_init() {
	if File_camera_camera_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_camera_camera_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Camera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCamerasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCamerasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_camera_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camera_camera_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camera_camera_proto_goTypes,
		DependencyIndexes: file_camera_camera_proto_depIdxs,
		MessageInfos:      file_camera_camera_proto_msgTypes,
	}.Build()
	File_camera_camera_proto = out.File
	file_camera_camera_proto_rawDesc = nil
	file_camera_camera_proto_goTypes = nil
	file_camera_camera_proto_depIdxs = nil
}
